language: go
env:
  global:
  - GIT_DEPLOY_DIR=public
  - GIT_DEPLOY_BRANCH=master
  - GIT_DEPLOY_USERNAME="abdul dakkak"
  - GIT_DEPLOY_EMAIL=abduld@wolfram.com
  - secure: eLZ9f6vdmQJhk3p+UuvYXh5Ah0hwhSCXf0X34HIHG7XM1jXdvmhAC3B5z1ZB2JoPFUVjrUsdV7FTnA9uVSJfHxiqXjZY/TwEFiUZHVbfznF2U1jMPYNfpQM4xi024LwR1kKvkkDKB2z/SFmkKemcrsPVo90rkQUDtcHIKspd694TRA6Rqa9Z5pOwiumfWBuu0H2ey/0N4M3VIhSPZMFyHhfAzYwl+SCgw9fB5hfKDOFsh73Mv1VFf+3HT9R6F5FDKMCis7UrFLhPS3O/5BM0ZzB0DGyxRelwpWQDUB/9mzZuPVIILLJNl7TsFilJuwcW2xEpyJQTtumDoRMtgz8dpWpib8dc3TO+v9Ro1/UfYkc8EcMlH3yLOtq2ceyzEv0P13ifnrsBTvMZeTMTqHKwPaMoQe6NAXaGomvRM+bqsbqxfvZq7VTvZfNheQXyjGNWzAcOAocYAaAC1ecBZUbCCK+5GHMOLIA/CCXJ14PIbhaY2PZ4S9DhUViFzaNPgl55cx6UcZAvQ186t2GxadGjma047ByabTeIhN8ri504mpTKmMUvLyN3T0LlaoDFLVCI5nbcfFJkBcwoIDWnA3va0j4A3wXxeRmqW/uYO/UkUD9jucZH72XDLA2ZNNHQBw1Eg4NPvbfRKdWtfTSdB5F5+7fEt2ReBt83JF+NL7cNYsc=
branches:
  only:
  - sources
install:
- rm -rf public || exit 0
script:
- binaries/hugo
after_success:
- cp .travis.yml public
- bash deploy.sh -v
