language: go
env:
  global:
  - GIT_DEPLOY_DIR=public
  - GIT_DEPLOY_BRANCH=master
  - GIT_DEPLOY_USERNAME="Abdul Dakkak"
  - GIT_DEPLOY_EMAIL=dakkak@illinois.edu
  - secure: "Btzt0cZ4z2mwpd/WPDXn4U+oy9rwdE1SSydinNBcIV8Ybv4iWCrfiJNyPAN/fm3FiBwEcx4yM7jDxaxzMSlCrz3NPv11maHx4EGJLlfyO7upSj4k4OUDTv0YFVXzAjlweJ6sZjhp1sBKhA60qcDqdTu91TtE9K3XLNHgM8cg6u5ieL2QHFGfWuYu+ky3nSgQ38FNPpwVWwJr326m+zKYcXkW2k+MWHh0JzdUvsGKwQx8zVMuEY9PYJBPOGvBBmBVx7C0c/uMtFp4dVxb5lAotr3hDPn91uSFiftquT+rnCWsf4VS2C0aM9Odd7kFSVYVBphaH5w6Ljq7iRFzJ8PyBzVgEJ+WA7etEVRjYVlopjohwOeO9zjTwzjMczMVSPbgisy6LZBbR5a2Wdh4H4L09LSTYG/caswB1ZuJJSmw9hMcsePUSfo0SvSxLIoKPygxPfNIPs3E2FPAa10HsCRKI/uqOEKMdv56ryN0a1i37RpIAxDUc+JWdnSqIpLs5ofs0+Ft5UjitVvkkKaLZeKnz+tVc7qmYJryiaRh3ObNkYGPZ1TU4fKNKf+c9UVVeTZ+5Y4OqCXsJfGcHQXK/mrDShr2zzhuONKjskxNu4yRPQ5Z61+hpcDSq2O0f7rRg1qFt35gpn/XENBI1w9B2L/532d95sC5hly8qmjITVZQoC4="
branches:
  only:
  - sources
install:
- rm -rf public || exit 0
script:
- binaries/hugo # generate!
after_success:
- cp .travis.yml public
- bash deploy.sh -v
