language: go
env:
  global:
  - GIT_DEPLOY_DIR=public
  - GIT_DEPLOY_BRANCH=master
  - GIT_DEPLOY_USERNAME="abdul dakkak"
  - GIT_DEPLOY_EMAIL=abduld@wolfram.com
  - secure: PwDgV3Yr1TXhmBv8vR7h7WKb2hulsbrP8w0S3RO2dDgFY8DlieExLothTF9A7lreMs10m8YeNGn7+WZ/rZ0mXMDoQYUBJ8A9m7BiIb77p1ekYDniJUF6Ce52Xnd0NR4DJ7gkcb5hARAuufN9S+f+kCKJH/kbBEt2IalpOpTMZipQfp5f0mhn3ypD8aZxjCwf0GcW8QeKXDCOq779sGqNDlIpwdJSVs9DM1HvyVDzSqJROfj80xxnYHVss8VM7JIeqSJN5IkdQrRk1JF3/sCDfWV8+/VD0bWd1Q0ZUuR3+MtMqZ0xWAx4YayXgH6/8/H86W3PPkcuU05Arpv+6gsdL06zmLG7YLYqLPFInzMozW5GytkzlqwyA39QLYnMmYzeweuVhREo5Z6La6fgo3+HMkJ0npAw74x7gN74bLR/UvtBvMhbX7Qd0UiE+k9uJDU3IdH7766XMIi4VlrCmAssOkuSo7tC0Op+kpzDeFxf6Lo3wyoui4/qhBwBblkGKioLDWw6h7VisYnQiwi/l3xOQHE2GCt0pD8gmONY5tf3d0I/4a8VPCJPVDP4/rCQ3f8DCbv3oQPQxmdjDGoPmd2le65Td5RCq4PlZNaJyrj0EBRFWpYRcwr1ZphfTFfq32DgVlEbIBBbthmR0Pl/P3jO5mlw/DXI3RyHiNzshPTbFk4=
branches:
  only:
  - sources
install:
- rm -rf public || exit 0
script:
- binaries/hugo
after_success:
- cp .travis.yml public
- bash deploy.sh -v
